#!/usr/bin/env python
"""Regenerate the per-document page selection used by the regression tests.

The regression corpus grows by whole documents, but verifying every page of
every document is neither affordable nor informative: consecutive pages of the
same PDF exercise the same code paths. This script picks a small, stable
sample per document and writes it to ``tests/regression_page_selection.py``.

Selection rules, in order of precedence:

1. ``PINNED_PAGES`` wins outright. Those documents are in the corpus for one
   specific page, or are too large to sample blindly.
2. ``ALWAYS_KEEP_PAGES`` are always selected. They are the pages that once
   failed the parser regression, and they stay in so a fix cannot silently
   regress. A document may therefore end up with more than ``MAX_PAGES``.
3. Documents with at most ``MAX_PAGES`` pages keep all of their pages.
4. Everything else is topped up to ``MAX_PAGES`` with pages drawn from a
   generator seeded by the document name, so the sample is reproducible and
   changing one document never reshuffles another.

Usage:

    uv run python tests/tools/select_regression_pages.py [--max-pages 5] [--check]
"""

from __future__ import annotations

import argparse
import glob
import os
import random
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

# Deliberately not imported from tests.constants: that module reads the file
# this script generates, so it cannot be a prerequisite for generating it.
REGRESSION_DIR = REPO_ROOT / "tests" / "data" / "regression"
OUTPUT_PATH = REPO_ROOT / "tests" / "regression_page_selection.py"

MAX_PAGES = 5

# Documents whose page selection is deliberate and must not be sampled.
PINNED_PAGES = {
    "deep-mediabox-inheritance.pdf": [2],
    "font_06.pdf": [1],
    "font_07.pdf": [1],
    "font_08.pdf": [1],
    "font_09.pdf": [1],
    "font_10.pdf": [1],
    "font_11.pdf": [1, 2],
    "2508.13113v2.pdf": [2, 9, 17],
    "dln-v1.pdf": [1],
    "PDF32000_2008.pdf": [1, 2],
}

# Pages that have exposed a parser defect. They are kept regardless of the
# sample so the corresponding fix keeps being exercised.
ALWAYS_KEEP_PAGES = {
    # zero-area and sub-pixel image placements
    "11033738705194660817-2.pdf": list(range(2, 19)),
    "11273518440839632455_002.pdf": [1, 4],
    "11502661831409318491_002.pdf": [2],
    "14570626672493314948-53.pdf": [34, 35, 37, 38, 39],
    "14911938403731335361-1.pdf": [1, 2],
    "15424333971388669153-2.pdf": [3],
    "3763025099401294496-2.pdf": list(range(2, 16)),
    "7413869934284023443-1.pdf": [2],
    "8e83c3f10f9f6093_0001.pdf": [1],
    "da04f7ddb6f59004_0025.pdf": [1],
    "ead2c552b489aac1_0004.pdf": [1],
    # CID codes that no cmap resolves, previously leaked as raw code bytes
    "skipped_1page.pdf": [2],
    "skipped_2pages.pdf": [2, 3],
}


def count_pages(path: str) -> int:
    import warnings

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        import pypdf

        return len(pypdf.PdfReader(path, strict=False).pages)


def select_pages(name: str, n_pages: int, max_pages: int) -> list[int]:
    if name in PINNED_PAGES:
        return sorted(p for p in PINNED_PAGES[name] if 1 <= p <= n_pages)

    all_pages = list(range(1, n_pages + 1))

    selected = {p for p in ALWAYS_KEEP_PAGES.get(name, []) if 1 <= p <= n_pages}

    if n_pages <= max_pages:
        selected.update(all_pages)
    else:
        candidates = [p for p in all_pages if p not in selected]
        rng = random.Random(name)
        rng.shuffle(candidates)
        selected.update(candidates[: max(0, max_pages - len(selected))])

    return sorted(selected)


def build_selection(max_pages: int) -> dict[str, list[int]]:
    pdf_paths = sorted(glob.glob(str(REGRESSION_DIR / "*.pdf")))
    if not pdf_paths:
        raise SystemExit(f"no PDFs found under {REGRESSION_DIR}")

    return {
        os.path.basename(p): select_pages(
            os.path.basename(p), count_pages(p), max_pages
        )
        for p in pdf_paths
    }


def render_module(selection: dict[str, list[int]], max_pages: int) -> str:
    lines = [
        '"""Pages of the regression corpus that the test-suite decodes and verifies.',
        "",
        "Generated by ``tests/tools/select_regression_pages.py``; do not edit by hand.",
        f"At most {max_pages} pages per document, plus every page pinned or known to",
        "have exposed a defect. Re-run the script after adding documents to",
        "``tests/data/regression``.",
        '"""',
        "",
        "from typing import Dict, List",
        "",
        "REGRESSION_PAGE_SELECTION: Dict[str, List[int]] = {",
    ]

    for name, pages in selection.items():
        rendered_pages = ", ".join(str(p) for p in pages)
        lines.append(f'    "{name}": [{rendered_pages}],')

    lines.append("}")
    lines.append("")

    return ruff_format("\n".join(lines))


def ruff_format(source: str) -> str:
    """Run the repository formatter, so ``--check`` agrees with pre-commit."""
    import subprocess

    try:
        completed = subprocess.run(
            ["ruff", "format", "--stdin-filename", str(OUTPUT_PATH), "-"],
            input=source,
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError) as exc:
        print(f"skipping ruff format: {exc}", file=sys.stderr)
        return source

    return completed.stdout


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--max-pages", type=int, default=MAX_PAGES)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when the file is out of date",
    )
    args = parser.parse_args()

    selection = build_selection(args.max_pages)
    rendered = render_module(selection, args.max_pages)

    n_docs = len(selection)
    n_pages = sum(len(v) for v in selection.values())
    print(f"{n_docs} documents, {n_pages} selected pages")

    if args.check:
        current = (
            OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
        )
        if current != rendered:
            print(f"{OUTPUT_PATH} is out of date", file=sys.stderr)
            return 1
        return 0

    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
